GAMEOVER_FORFEIT = 0
GAMEOVER_WIN = 1
GAMEOVER_LOSE = 2
GAMEOVER_SAVE = 3
GAMEOVER_LOAD = 4

GAMEOVER_STATES = {
    GAMEOVER_FORFEIT,
    GAMEOVER_WIN,
    GAMEOVER_LOSE,
    GAMEOVER_SAVE,
    GAMEOVER_LOAD,
}

GAME_CONTINUE = 5